# Generated by Django 3.2 on 2021-05-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(max_length=32)),
                ('claim_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('claim_count', models.IntegerField(default=0)),
                ('item_type', models.SmallIntegerField(choices=[(1, 'Single'), (2, 'Multiple')], default=1)),
                ('category', models.ManyToManyField(blank=True, to='registry.Claim')),
            ],
        ),
    ]
