# Generated by Django 3.2 on 2021-05-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_item_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
