# Generated by Django 3.2 on 2021-05-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_claim_email_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='claim_id',
            new_name='claim_key',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='claim_email',
            new_name='email_address',
        ),
    ]
