# Generated by Django 3.2 on 2021-05-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_alter_claim_claim_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='og_desciption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='og_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='og_title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
