# Generated by Django 3.2 on 2021-05-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_auto_20210506_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='og_meta',
            field=models.BooleanField(default=False),
        ),
    ]
