# Generated by Django 3.2 on 2021-05-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_item_og_meta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='og_desciption',
            new_name='og_description',
        ),
    ]
