# Generated by Django 3.2 on 2021-05-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_rename_og_desciption_item_og_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='claim_count',
            new_name='want_count',
        ),
    ]
