# Generated by Django 3.2 on 2021-06-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_rename_claim_count_item_want_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='want_count',
            field=models.IntegerField(default=1),
        ),
    ]
